name: Phpunit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8]

    name: 'PHP ${{ matrix.php }}'

    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: '${{ matrix.php }}'

      - uses: actions/checkout@v2

      # 特殊情况举例
      # - name: Install legacy factories for Laravel
      #   if: ${{ matrix.laravel == '8.*' }}
      #   run: composer require laravel/legacy-factories

      - name: Composer Update
        run: composer self-update --2

      - name: Install
        run: composer install --no-interaction

      - name: Run test suite
        run: ./vendor/bin/phpunit

